### ISSUE TITLE
Si hay un error en la conexion con la base de datos -> Impedir el arranque del servidor

### ISSUE THREAD

**Issue by ojcgv21** [XPeru/XWebApp#2]
El servidor arranca bien incluso si ha habido algun error en la creacion del pool mysql, deberiamos levantar alguna excepcion para impedir el arranque del servidor, y advertir al developer.

Archivos implicados:
- server.js
- connectMysql.js

Ejm:
Al cambiar el password por uno cualquiera en el archivo `.env.dev` observamos que le servidor arranca correctamente.

**Comment by eduapb** [comment]
Para corregir ese detalle se envía una query simple al momento de crear el pool.
De acuerdo al resultado, se agrega lo siguiente en el log del servidor:
* Conexión exitosa
<img width="565" alt="screen shot 2017-09-17 at 13 09 03" src="https://user-images.githubusercontent.com/11872428/30517926-71cdd92c-9ba9-11e7-9ed2-eaa781fd1aee.png">

* Conexión fallida
<img width="787" alt="screen shot 2017-09-17 at 13 10 33" src="https://user-images.githubusercontent.com/11872428/30517932-a52b2b3a-9ba9-11e7-8abd-4ba83fd6e7eb.png">

**Comment by ojcgv21** [comment]
@eduapb Aprobado XD
